[build]
  command = "npm install && prisma generate && npm run build"
  environment = { NODE_ENV = "production", GO_VERSION = "1.19" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.cache]
  # Ignore Prisma Client cache to prevent using outdated versions
  ignore = ["node_modules/@prisma/client"]
